name: Matrix with Node.js
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        version: [14, 16, 17]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.version }}
    - run: npm install
    - name: Running on Platform = ${{ matrix.platform }} Node = ${{ matrix.version }}
      run: npm test
